GET http://localhost:8000/ping
###
GET http://localhost:8000/users
###
GET http://localhost:8000/users?status=active
# ?status=test
###
GET http://localhost:8000/users/1
###
POST http://localhost:8000/users
content-type: application:json

{
  "id": 1,
  "first_name": "Adnin",
  "last_name": "Rifandi",
  "email": "cccc",
  "date_created": "2021-06019",
  "status": "",
  "password": "null"
}
###
PATCH http://localhost:8000/users/1
content-type: application:json

{
  "id": 1,
  "first_name": "Rifandi",
  "last_name": "Adninaaa",
  "email": "aaaa",
  "status": null,
  "password": null
}
###
DELETE http://localhost:8000/users/1
content-type: application:json
###